### ISSUE TITLE
No TLS does not work

### ISSUE THREAD

**Issue by minhnq1618** [offsecginger/CTFd-Docker-Challenges#3]
Hello, i am back :D and i manage to make the plugin work halfway :/

If i don't use TLS then i can get the docker repos

![image](https://user-images.githubusercontent.com/81002476/113999003-cea52800-9883-11eb-97c7-d8acb2ab87bb.png)

But the instances could not be create when the challenge start.

![image](https://user-images.githubusercontent.com/81002476/113999159-f98f7c00-9883-11eb-8c1f-200d4987ca4e.png)

This error show in the log

![image](https://user-images.githubusercontent.com/81002476/113999257-1330c380-9884-11eb-9d82-98e739f104cc.png)

Now if i decided to use TLS i could not get the repos

![image](https://user-images.githubusercontent.com/81002476/113999830-9b16cd80-9884-11eb-8fde-120bc350fdbc.png)

But from the command line i can get to it

![image](https://user-images.githubusercontent.com/81002476/113999785-8df9de80-9884-11eb-82a6-7b3369a406e2.png)

Can you make the plugin to work with no TLS please ?

**Comment by Ketherz** [comment]
TLS work fine with me :'(

![image](https://user-images.githubusercontent.com/1362237/114000841-a6a1ce80-985b-11eb-966a-6310ccd27ecb.png)

Don't you have any logs that appear on the docker daemon when you try to connect from the website with TLS? Some logs that said something like : "we received something from this IP, but we expect that from another IP" (Yeah sorry it's not very explicit haha, but i ran into a similar error last month and i don't have any logs)

Btw thanks @offsecginger for your last answer on the other post, i couldn't respond because it was closed.

**Comment by minhnq1618** [comment]
My docker daemon show nothing LOL
![image](https://user-images.githubusercontent.com/81002476/114004887-44f85900-9889-11eb-9fd3-7ded9c70a51f.png)

Lets me try to do the local docker daemon with TLS to see if that work for me

**Comment by minhnq1618** [comment]
Hi @Ketherz, i tried the local Docker daemon and it still did not work with TLS :(, if i don't use TLS then it work :(

I noticed that during the steps to make certificate for the Docker daemon from [https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket](https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket), there is this `$HOST` variables, what do you use for this ? i tried both the `IP` or `Hostname` of the server but both time did not work. But i am thinking that this could be reason why it did not work :/

**Comment by offsecginger** [comment]
@minhnq1618 I think I know what's wrong.

What version of python are you using for CTFd? Also upgrade to 3.3.0 and pull the latest docker plugin. Regenerate your cert. Replace $HOST in your openssl command with the hostname but also make sure to replace that 10.10 address with your address of your docker Server. Finally start the docker daemon without the service. Stop the service and run the dockerd command in that tutorial. Be sure to use the client keys and certificates for CTFd connections. I just rewrote parts of this plugin and I know it's working with TLS in python3. I want to make sure we get you squared away. Feel free to DM and I'll send you a link to schedule a meeting. My twitter is @ offsec_ginger

**Comment by Ketherz** [comment]
Yep the variable $HOST is realy important it is the address of the docker deamon, if i remember well for me it was the loopback address 127.0.0.1! For you it will maybe be challenges.com. 
I advise you to restart the TLS setup process with the good variables names. Btw, if you have no log when you try to connect, maybe challenges.com do not ping the good address? Maybe you should try with the IP of the docker daemond?

**Comment by minhnq1618** [comment]
@offsecginger i am using python3 only, still could not make it work after all that :( not sure where i am wrong.

I will send you a DM later.

**Comment by minhnq1618** [comment]
@offsecginger , i could not DM you :(

![image](https://user-images.githubusercontent.com/81002476/114061280-73ddf180-98c0-11eb-9fe2-8682e62e7332.png)

My twitter is @ imanalysiz

**Comment by minhnq1618** [comment]
Plugin work now so i am closing this issue, thank again @offsecginger and you too @Ketherz  for your help  :+1:

**Comment by vnthn** [comment]
Hi, I think I am having the exact same problem as @minhnq1618. Could you tell me what did the trick to solve this issue?
I am using Python 3.8.5 with Flask 1.1.2 and Werkzeug 1.0.1 on Ubuntu 20.04.2 LTS and a fresh cloned CTFd and a fresh clone of this repo. I can confirm that the plugin does work halfway without TLS as described by @minhnq1618, but when using TLS the Docker daemon doesn't show anything in the logs, even in debug mode. Connecting with docker The certificates are issued to "company-name-ctf". This hostname is assigned 127.0.0.1. I also tried to issue the certificate to "localhost" and to "127.0.0.1". Both do not work. I also added the hostname "client" to /etc/hosts because the client certificate is issued to this common name.
What am I missing or doing wrong?

**Comment by offsecginger** [comment]
You must follow the TLS guide for docker. Also if you don't have any images
it will still say failed to connect.
https://docs.docker.com/engine/security/protect-access/
